// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enums.proto
// Protobuf C++ Version: 5.29.0

#ifndef Enums_2eproto_2epb_2eh
#define Enums_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enums_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enums_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enums_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum EmployeeStatus : int {
  NORMAL = 0,
  ONVACATION = 1,
  RESIGNED = 2,
  RETIRED = 3,
  EmployeeStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EmployeeStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EmployeeStatus_IsValid(int value);
extern const uint32_t EmployeeStatus_internal_data_[];
constexpr EmployeeStatus EmployeeStatus_MIN = static_cast<EmployeeStatus>(0);
constexpr EmployeeStatus EmployeeStatus_MAX = static_cast<EmployeeStatus>(3);
constexpr int EmployeeStatus_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
EmployeeStatus_descriptor();
template <typename T>
const std::string& EmployeeStatus_Name(T value) {
  static_assert(std::is_same<T, EmployeeStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EmployeeStatus_Name().");
  return EmployeeStatus_Name(static_cast<EmployeeStatus>(value));
}
template <>
inline const std::string& EmployeeStatus_Name(EmployeeStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EmployeeStatus_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool EmployeeStatus_Parse(absl::string_view name, EmployeeStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EmployeeStatus>(
      EmployeeStatus_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EmployeeStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::EmployeeStatus>() {
  return ::EmployeeStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enums_2eproto_2epb_2eh
