// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enums.proto
// Protobuf C++ Version: 5.29.0

#include "Enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enums_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Enums_2eproto = nullptr;
const ::uint32_t TableStruct_Enums_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Enums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013Enums.proto*G\n\016EmployeeStatus\022\n\n\006NORMA"
    "L\020\000\022\016\n\nONVACATION\020\001\022\014\n\010RESIGNED\020\002\022\013\n\007RET"
    "IRED\020\003B\030\252\002\025GrpcServer.Web.Protosb\006proto3"
};
static ::absl::once_flag descriptor_table_Enums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Enums_2eproto = {
    false,
    false,
    120,
    descriptor_table_protodef_Enums_2eproto,
    "Enums.proto",
    &descriptor_table_Enums_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_Enums_2eproto::offsets,
    file_level_enum_descriptors_Enums_2eproto,
    file_level_service_descriptors_Enums_2eproto,
};
const ::google::protobuf::EnumDescriptor* EmployeeStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Enums_2eproto);
  return file_level_enum_descriptors_Enums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EmployeeStatus_internal_data_[] = {
    262144u, 0u, };
bool EmployeeStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Enums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
